version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - e_folder_db
  e_folder_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: e_folder_database
      MYSQL_USER: e_folder
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

